// @vitest-environment node
// Codegen is pure Node — it reads its built-in .tt templates from disk relative
// to import.meta.url, which jsdom would root at "/". Run under node so the real
// file URL resolves.
import { describe, expect, it } from "vitest";
import { android, ios, web } from "./codegen";
import type { Site } from "../engine/model";
import type { RegistryFile } from "../engine/schema";

// Prop VALUES are JS expression source: `"$props.title"` is a binding, `"'/a.png'"`
// a literal string. Children are component instances and literal text strings —
// a node always instances a registered component, never a raw host tag.
const registry: RegistryFile = {
  components: {
    "@/components/ui/icon#Icon": { import: { module: "@/components/ui/icon", name: "Icon" }, props: {} },
  },
};
// Code components are addressed by their registry id (`@/module#Export`); bare
// names are the design's own namespace.
const ICON = "@/components/ui/icon#Icon";
const site: Site = {
  components: [
    {
      // A component IS a node: type/props/children directly, no `root` wrapper.
      // A UI-created component's root carries the reserved type "Custom".
      name: "Card",
      type: "Custom",
      props: { title: "$props.title", onClick: "$ctx.toggle()" },
      children: [
        "Hello",
        { type: ICON, props: { src: "'/a.png'" }, children: [] },
        { type: "Slot", props: {}, children: [] },
      ],
    },
  ],
};

describe("web target", () => {
  const [file] = web({ out: "./dist" }).generate(site, { root: "/x", registry });

  it("emits one .tsx per component", () => {
    expect(file.path).toBe("Card.tsx");
  });

  it("prepends a DO-NOT-EDIT banner to generated files", () => {
    expect(file.content.startsWith("// This file is auto-generated by cnstudio — DO NOT EDIT.")).toBe(true);
  });

  it("sources $ctx from useDataEnv (data binding, no state)", () => {
    expect(file.content).toContain('import { useDataEnv } from "@cnstudio-io/cnstudio/react-web";');
    expect(file.content).toContain("const $ctx: Record<string, any> = useDataEnv();");
    expect(file.content).not.toContain("use$State");
  });

  it("emits prop expressions, an event handler, and the slot", () => {
    expect(file.content).toContain('export function Card($props: Record<string, any> = {})');
    expect(file.content).toContain("title={$props.title}"); // a prop-value binding
    expect(file.content).toContain("onClick={() => { $ctx.toggle() }}"); // no event ref → no param
    expect(file.content).toContain("<Icon src={'/a.png'} />"); // literal string prop value
    expect(file.content).toContain("{$props.children}"); // slot
  });

  it('emits a "Custom" root as a plain <div> wrapper', () => {
    expect(file.content).toContain("<div title={$props.title}");
  });
});

describe("named slots", () => {
  // Shell declares a named "header" slot plus the default slot; Page instances
  // it, routing one child to "header" via the reserved `slot` prop.
  const slotted: Site = {
    components: [
      {
        name: "Shell",
        type: "Custom",
        props: {},
        children: [
          { type: "Slot", props: { name: "header" }, children: [] },
          { type: "Slot", props: {}, children: [] },
        ],
      },
      {
        name: "Page",
        type: "Custom",
        props: {},
        children: [
          {
            type: "Shell",
            props: {},
            children: [
              { type: ICON, props: { slot: "header", src: "'/a.png'" }, children: [] },
              "body",
            ],
          },
        ],
      },
    ],
  };
  const files = web({ out: "./d" }).generate(slotted, { root: "/x", registry });
  const shell = files.find((f) => f.path === "Shell.tsx")!;
  const page = files.find((f) => f.path === "Page.tsx")!;

  it("emits pickSlot filters for every marker once any marker is named", () => {
    expect(shell.content).toContain('{pickSlot($props.children, "header")}');
    expect(shell.content).toContain('{pickSlot($props.children, "")}');
    expect(shell.content).not.toContain("{$props.children}");
    expect(shell.content).toContain('import { pickSlot } from "@cnstudio-io/cnstudio/react-web";');
  });

  it("emits the routing prop as a literal string attribute, not an expression", () => {
    expect(page.content).toContain('slot={"header"}');
  });

  it("emits a forwarding marker (a fill that is itself a Slot) with its reroute target", () => {
    // Wrap declares slot "page" and forwards it into Shell's "header" slot: the
    // marker is a fill (slot: "header") and a declaration (name: "page") at once.
    const forwarding: Site = {
      components: [
        slotted.components[0], // Shell (declares "header" + an unnamed marker)
        {
          name: "Wrap",
          type: "Custom",
          props: {},
          children: [
            {
              type: "Shell",
              props: {},
              children: [{ type: "Slot", props: { name: "page", slot: "header" }, children: [] }],
            },
          ],
        },
      ],
    };
    const wrap = web({ out: "./d" })
      .generate(forwarding, { root: "/x", registry })
      .find((f) => f.path === "Wrap.tsx")!;
    expect(wrap.content).toContain('{pickSlot($props.children, "page", "header")}');
  });

  it("keeps the plain children passthrough for a component with only unnamed markers", () => {
    const [file] = web({ out: "./d" }).generate(site, { root: "/x", registry });
    expect(file.content).toContain("{$props.children}");
    expect(file.content).not.toContain("pickSlot");
  });
});

describe("path-like component names", () => {
  // A page named `page/calendar` emits to `page/calendar.tsx`, exports the
  // sanitized basename, and reaches a root-level sibling via `../`.
  const paged: Site = {
    components: [
      {
        name: "AppShell",
        type: "Custom",
        props: {},
        children: [{ type: "Slot", props: { name: "main" }, children: [] }],
      },
      {
        name: "page/calendar",
        type: "Custom",
        props: {},
        children: [
          {
            type: "AppShell",
            props: {},
            children: [{ type: ICON, props: { slot: "main" }, children: [] }],
          },
        ],
      },
    ],
  };
  const files = web({ out: "./d" }).generate(paged, { root: "/x", registry });

  it("emits the file under the path and exports the basename", () => {
    const page = files.find((f) => f.path === "page/calendar.tsx")!;
    expect(page).toBeDefined();
    expect(page.content).toContain("export function calendar(");
  });

  it("imports a sibling design component relative to the page's depth", () => {
    const page = files.find((f) => f.path === "page/calendar.tsx")!;
    expect(page.content).toContain('import { AppShell } from "../AppShell";');
    expect(page.content).toContain("<AppShell>");
  });
});

describe("invalid nodes", () => {
  it("rejects a raw host tag — a node must instance a registered component", () => {
    const bad: Site = {
      components: [
        { name: "Card", type: "Custom", props: {}, children: [{ type: "div", props: {}, children: [] }] },
      ],
    };
    expect(() => web({ out: "./d" }).generate(bad, { root: "/x" })).toThrow(
      /<div>: not a design component/
    );
  });
});

describe("code-component imports", () => {
  const registry: RegistryFile = {
    components: {
      "@/components/ui/button#Button": { import: { module: "@/components/ui/button", name: "Button" }, props: {} },
    },
  };
  const withButton: Site = {
    components: [
      {
        name: "Bar",
        type: "Custom",
        props: {},
        children: [{ type: "@/components/ui/button#Button", props: { variant: "'ghost'" }, children: ["Go"] }],
      },
    ],
  };

  it("imports registered code components from their real module", () => {
    const [file] = web({ out: "./d" }).generate(withButton, { root: "/x", registry });
    expect(file.content).toContain('import { Button } from "@/components/ui/button";');
    expect(file.content).toContain("<Button variant={'ghost'}>");
  });
});

describe("name resolution", () => {
  it("rejects a bare code-component export name — code components are addressed by registry id", () => {
    const bare: Site = {
      components: [
        { name: "Card", type: "Custom", props: {}, children: [{ type: "Icon", props: {}, children: [] }] },
      ],
    };
    expect(() => web({ out: "./d" }).generate(bare, { root: "/x", registry })).toThrow(
      /<Icon>: not a design component/
    );
  });

  it("lets a design component share a code component's export name without colliding", () => {
    const reg: RegistryFile = {
      components: {
        "@/components/ui/card#Card": { import: { module: "@/components/ui/card", name: "Card" }, props: {} },
      },
    };
    const shadow: Site = {
      components: [
        // The design's own "Card" — a bare reference resolves here…
        { name: "Card", type: "Custom", props: {}, children: [] },
        {
          name: "Page",
          type: "Custom",
          props: {},
          children: [
            { type: "Card", props: {}, children: [] },
            // …while the code component is addressed by id and gets an alias.
            { type: "@/components/ui/card#Card", props: {}, children: [] },
          ],
        },
      ],
    };
    const files = web({ out: "./d" }).generate(shadow, { root: "/x", registry: reg });
    const page = files.find((f) => f.path === "Page.tsx")!;
    expect(page.content).toContain('import { Card } from "./Card";');
    expect(page.content).toContain('import { Card as Card$2 } from "@/components/ui/card";');
    expect(page.content).toContain("<Card />");
    expect(page.content).toContain("<Card$2 />");
  });

  it("aliases same-named exports from different modules", () => {
    const reg: RegistryFile = {
      components: {
        "@/a#Icon": { import: { module: "@/a", name: "Icon" }, props: {} },
        "@/b#Icon": { import: { module: "@/b", name: "Icon" }, props: {} },
      },
    };
    const two: Site = {
      components: [
        {
          name: "Pair",
          type: "Custom",
          props: {},
          children: [
            { type: "@/a#Icon", props: {}, children: [] },
            { type: "@/b#Icon", props: {}, children: [] },
          ],
        },
      ],
    };
    const [f] = web({ out: "./d" }).generate(two, { root: "/x", registry: reg });
    expect(f.content).toContain('import { Icon } from "@/a";');
    expect(f.content).toContain('import { Icon as Icon$2 } from "@/b";');
  });
});

describe("variants", () => {
  const variantSite: Site = {
    components: [
      {
        name: "Box",
        variantNames: ["active"],
        type: "Custom",
        props: { className: "'box'" },
        variants: { active: { className: "'box on'" } },
        children: ["hi"],
      },
    ],
  };

  it("emits applyVariant() driven by $props.activeVariant", () => {
    const [file] = web({ out: "./d" }).generate(variantSite, { root: "/x" });
    expect(file.content).toContain('import { applyVariant } from "@cnstudio-io/cnstudio/react-web";');
    expect(file.content).toContain(
      '{...applyVariant({ "className": \'box\' }, $props.activeVariant, { "active": { "className": \'box on\' } })}'
    );
  });
});

describe("loops", () => {
  const loopSite: Site = {
    components: [
      {
        name: "List",
        type: "Custom",
        props: {},
        children: [
          {
            type: "Loop",
            props: { data: "$ctx.groups", name: "group" },
            children: [
              { type: ICON, props: { title: "$loop.group.current.label" }, children: [] },
              {
                type: "Loop",
                props: { data: "$loop.group.current.children", name: "leaf" },
                children: [
                  { type: ICON, props: { title: "$loop.leaf.current.label" }, children: [] },
                ],
              },
            ],
          },
        ],
      },
    ],
  };
  const [file] = web({ out: "./d" }).generate(loopSite, { root: "/x", registry });

  it("emits data.map with $loop bound under the loop name", () => {
    expect(file.content).toContain('import { Fragment } from "react";');
    expect(file.content).toContain("(Array.isArray(__data) ? __data : []).map((current: any, index: number, all: any[])");
    expect(file.content).toContain('const $loop: Record<string, any> = { ...__outer, "group": { current, index, all } };');
    expect(file.content).toContain("title={$loop.group.current.label}");
    expect(file.content).toContain("<Fragment key={index}>");
  });

  it("threads the enclosing $loop into a nested loop (outer env is {} at the top)", () => {
    expect(file.content).toContain("}))($ctx.groups, {})}");
    expect(file.content).toContain("}))($loop.group.current.children, $loop)}");
    expect(file.content).toContain('{ ...__outer, "leaf": { current, index, all } }');
  });

  it("skips the $loop binding when the template never reads it", () => {
    const staticLoop: Site = {
      components: [
        {
          name: "Dots",
          type: "Custom",
          props: {},
          children: [
            { type: "Loop", props: { data: "$ctx.items" }, children: [{ type: ICON, props: {}, children: [] }] },
          ],
        },
      ],
    };
    const [f] = web({ out: "./d" }).generate(staticLoop, { root: "/x", registry });
    expect(f.content).not.toContain("const $loop");
    expect(f.content).toContain(".map((_current: any, index: number) => (");
  });
});

describe("hidden", () => {
  it("emits a conditional render mirroring the runtime, not a DOM attribute", () => {
    const hiddenSite: Site = {
      components: [
        {
          name: "Maybe",
          type: "Custom",
          props: {},
          children: [
            { type: ICON, props: { hidden: "$ctx.items.length === 0", src: "'/a.png'" }, children: [] },
          ],
        },
      ],
    };
    const [f] = web({ out: "./d" }).generate(hiddenSite, { root: "/x", registry });
    expect(f.content).toContain("{!($ctx.items.length === 0) && (");
    expect(f.content).toContain("<Icon src={'/a.png'} />");
    expect(f.content).not.toContain("hidden=");
  });
});

describe("custom template", () => {
  it("lets studio.config own the file shape, banner still enforced", () => {
    const [file] = web({
      out: "./d",
      template: (c) => `"use client";\n${c.imports}\nexport default function ${c.name}(${c.propsSig}) {\n${c.setup}  return (\n${c.tree}\n  );\n}\n`,
    }).generate(site, { root: "/x", registry });

    expect(file.content.startsWith("// This file is auto-generated by cnstudio — DO NOT EDIT.")).toBe(true);
    expect(file.content).toContain('"use client";');
    expect(file.content).toContain("export default function Card($props: Record<string, any> = {})");
    expect(file.content).toContain("title={$props.title}"); // tree hole filled
  });
});

describe("react native targets", () => {
  it("maps the Custom root to a View, imports only used host components, renames onClick→onPress", () => {
    const [file] = android({ out: "./android" }).generate(site, { root: "/x", registry });
    expect(file.path).toBe("Card.android.tsx");
    expect(file.content).toContain('import { Text, View } from "react-native";');
    expect(file.content).toContain("<View"); // Custom root → View on RN
    expect(file.content).toContain("onPress={() =>");
    expect(file.content).not.toContain("className");
  });

  it("wraps a bare literal-text child in <Text>", () => {
    const [file] = android({ out: "./android" }).generate(site, { root: "/x", registry });
    expect(file.content).toContain("<Text>Hello</Text>");
  });

  it("ios uses the .ios.tsx suffix", () => {
    const [file] = ios({ out: "./ios" }).generate(site, { root: "/x", registry });
    expect(file.path).toBe("Card.ios.tsx");
  });
});
