import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import ejs from "ejs";
import {
  instanceOf,
  type Component,
  type Node,
  type Site,
} from "../engine/model";
import type { ImportSpec, RegistryFile } from "../engine/schema";

/**
 * The codegen target API. `studio.config.js` declares a `codegen` array of
 * targets built by the platform factories:
 *
 * ```js
 * import { web, android, ios } from "@cnstudio-io/cnstudio/codegen";
 * export default {
 *   codegen: [
 *     web({ out: "./dist" }),
 *     android({ out: "./android" }),
 *     ios({ out: "./ios" }),
 *   ],
 * };
 * ```
 *
 * Each factory returns a {@link CodegenTarget}: a pure `generate(site, ctx)` that
 * maps the design model ({@link Site}) to a list of {@link GeneratedFile}s. The
 * CLI (`cnstudio generate`) loads the model + registry, runs every target, and
 * writes the files under each target's `out` dir.
 *
 * The output is thin component SOURCE that the consuming app compiles. It
 * delegates the few things that must match the canvas runtime
 * (`$state`, variant merge) to `@cnstudio-io/cnstudio/react-web`, while emitting the tree, the
 * expressions, and the imports as plain source. `web` emits React for the DOM;
 * `android`/`ios` emit React Native (compiled by a React Native app).
 */

/** Options common to every platform factory. */
export interface CodegenTargetOptions {
  /** Output directory for this target, relative to the project root. */
  out: string;
  /**
   * Owns the SHAPE of each generated file. The generator fills the holes
   * ({@link ComponentParts} — `imports`, `name`, `propsSig`, `setup`, `tree`)
   * and the template assembles them, Rails-generator style. Either:
   *   - a **path** to a `.tt` file (relative to the project root) using
   *     `<%= hole %>` tags, or
   *   - a `(parts) => string` function.
   * Defaults to the built-in per-platform template at
   * `@cnstudio-io/cnstudio/src/generators/<platform>/template.tsx.tt`. The DO-NOT-EDIT
   * {@link BANNER} is always prepended afterwards, regardless of template.
   */
  template?: string | TemplateFn;
}

/** A compiled template: fills {@link ComponentParts} into file source. */
export type TemplateFn = (parts: ComponentParts) => string;

/**
 * The holes the generator computes for one component, handed to a
 * {@link CodegenTargetOptions.template}. Everything is pre-rendered source; a
 * template just decides the layout around it (and may re-walk the tree itself
 * via {@link ComponentParts.renderTree}).
 */
export interface ComponentParts {
  /** Component name, e.g. `"Hero"`. */
  name: string;
  /** Assembled import block — code components, sibling `./Name`, host + runtime
   * imports. Ends with a trailing blank line so it drops straight in above the
   * component; `""` when nothing is imported. */
  imports: string;
  /** The function parameter, e.g. `$props: Record<string, any> = {}` (or
   * `_$props…` when props are unused, to satisfy a strict noUnused typecheck). */
  propsSig: string;
  /** `$`-binding lines that go inside the function body before `return`, e.g.
   * `  const $ctx: Record<string, any> = useDataEnv();\n`. `""` when none. A
   * convenience hole: a flat template can drop `<%- setup %>`; a control-flow
   * template can instead branch on {@link ComponentParts.needsCtx}. */
  setup: string;
  /** Whether `$ctx` is referenced (so a template emits the `useDataEnv()` line).
   * Drives the built-in templates via EJS slurp-mode control flow. */
  needsCtx: boolean;
  /** Whether `$props` is referenced (slots / variants / a `$props.` expr). When
   * false {@link ComponentParts.propsSig} names the param `_$props`. */
  needsProps: boolean;
  /** The rendered layer tree as JSX, indented for placement inside `return (…)`. */
  tree: string;
  /** The raw root node, for a template that wants to walk the tree itself. */
  node: Node;
  /** The tree walker, exposed so a custom template can render any node. */
  renderTree(node: Node, indent?: number): string;
}

/** Prepended to every generated file. Generated source is never hand-edited. */
export const BANNER =
  "// This file is auto-generated by cnstudio — DO NOT EDIT.\n" +
  "// Changes are overwritten on the next `cnstudio generate`.\n\n";

/** One file a target wants written, `path` relative to the target's `out` dir. */
export interface GeneratedFile {
  path: string;
  content: string;
}

/** Ambient info a target may need while generating. */
export interface CodegenContext {
  /** Project root (cwd). */
  root: string;
  /** The component registry — resolves code-component (`Button`, …) imports. */
  registry?: RegistryFile;
}

/** A configured output target — the value a platform factory returns. */
export interface CodegenTarget {
  /** Which platform this target emits for. */
  platform: "web" | "android" | "ios";
  /** Output directory, relative to the project root. */
  out: string;
  /** Map the design model to the files to write. Pure — does no I/O. */
  generate(site: Site, ctx: CodegenContext): GeneratedFile[];
}

// The platform factories (`web`, `android`, `ios`) live in their own generator
// dirs alongside their templates — `src/generators/<platform>/index.ts` — and are
// re-exported at the bottom of this file so `@cnstudio-io/cnstudio/codegen` stays the single
// import path. Each calls {@link makeFiles} with its {@link Platform}.

/**
 * Run every target against `site`, writing each {@link GeneratedFile} under the
 * target's `out` dir. Returns the absolute paths written.
 */
export function runCodegen(
  site: Site,
  targets: CodegenTarget[],
  ctx: CodegenContext
): string[] {
  const written: string[] = [];
  for (const target of targets) {
    const outDir = resolve(ctx.root, target.out);
    for (const file of target.generate(site, ctx)) {
      const dest = join(outDir, file.path);
      mkdirSync(dirname(dest), { recursive: true });
      writeFileSync(dest, file.content);
      written.push(dest);
    }
  }
  return written;
}

// ——— platforms ———

/**
 * A platform's emit rules. The web and React Native paths share one tree walk and
 * differ only in: the element a UI-created component's root (`Custom`) wraps its
 * children in, whether bare text must be wrapped (RN forbids raw strings outside
 * `<Text>`), which props are renamed / dropped, and the import line for the host
 * components used. (Nodes only ever instance registered components or the reserved
 * `Custom`/`slot` — there are no arbitrary host tags to map.)
 */
export interface Platform {
  /** The element a `Custom` root emits as: `div` (web) or `View` (React Native). */
  wrapperTag: string;
  /** Whether the wrapper renders its children as text (so no `<Text>` wrap). The
   *  DOM lets any element hold text; RN's `View` does not. */
  wrapperHoldsText: boolean;
  /** Whether a bare string/expr child must be wrapped (RN) when not already in text. */
  wrapText: boolean;
  /** Rename / drop a prop key; return null to drop it. */
  mapProp(key: string): string | null;
  /** Import line(s) for the host components actually used (`View`/`Text` on RN). */
  hostImports(usedHostTags: Set<string>): string;
}

/** The web (DOM) platform: the `Custom` wrapper is a `<div>`; props pass through. */
export const WEB: Platform = {
  wrapperTag: "div",
  wrapperHoldsText: true, // the DOM lets any element hold text
  wrapText: false,
  mapProp: (key) => key,
  hostImports: () => "", // DOM intrinsics need no import
};

/** The React Native platform (shared by `android` and `ios`): the `Custom`
 *  wrapper is a `<View>`, and bare text is wrapped in `<Text>`. */
export function reactNativePlatform(): Platform {
  return {
    wrapperTag: "View",
    wrapperHoldsText: false, // a View can't hold raw text — see wrapText
    wrapText: true,
    mapProp: (key) => {
      if (key === "className") return null; // RN has no className
      if (key === "onClick") return "onPress";
      return key;
    },
    hostImports: (used) =>
      used.size
        ? `import { ${[...used].sort().join(", ")} } from "react-native";\n`
        : "",
  };
}

// ——— emitter ———

/** Per-file emit context threaded through the walk. */
interface Ctx {
  site: Site;
  registry?: RegistryFile;
  p: Platform;
}

/** How a node's `type` resolves: another designed component, a registered code
 * component (with its import), or the reserved `Custom` wrapper. */
type Kind =
  | { kind: "instance" }
  | { kind: "code"; spec: ImportSpec }
  | { kind: "wrapper" };

function classify(type: string, ctx: Ctx): Kind {
  if (instanceOf({ type, props: {}, children: [] }, ctx.site)) return { kind: "instance" };
  // The registry is keyed by a unique id, so match a node's `type` against the
  // export name (the design references components by bare name).
  const meta = Object.values(ctx.registry?.components ?? {}).find((m) => m.import.name === type);
  if (meta) return { kind: "code", spec: meta.import };
  // The ONLY non-component type a valid model carries is the reserved `Custom`
  // (a UI-created component's root), emitted as the platform wrapper element. Any
  // other `type` is a raw host tag (`div`, `span`, `img`, …) — NOT a valid node
  // (the editor's `assertType` can never create one). Fail the build rather than
  // emit a bogus host element from a hand-edited / corrupt site.json.
  if (type === "Custom") return { kind: "wrapper" };
  throw new Error(
    `cannot generate <${type}>: not a registered component. A node may only ` +
      "instance a component from the registry (or the reserved `slot`); raw HTML " +
      "tags are not valid node types."
  );
}

/** What the tree walk collects, so the file header can be assembled correctly. */
interface Collected {
  /** Host components actually emitted (`View`/`Text` on RN) — for the import line. */
  hostTags: Set<string>;
  /** Other designed components referenced — emitted as `./Name` sibling imports. */
  modelComponents: Set<string>;
  /** Registered code components referenced → their import spec, keyed by local name. */
  codeComponents: Map<string, ImportSpec>;
  /** Every expression string in the tree (decides which `$` vars to bind). */
  exprs: string[];
  /** Whether a `<slot>` appears (so `$props.children` is referenced). */
  hasSlot: boolean;
  /** Whether any node carries variant overrides (so `$props.activeVariant` is read). */
  hasVariants: boolean;
}

/**
 * Generate one file per component for a target: resolve its template once, then
 * for each component compute the {@link ComponentParts}, render them, and prepend
 * the DO-NOT-EDIT {@link BANNER} (enforced here, whatever shape the template has).
 * `suffix` is the platform tag in the filename (`""` for web, `".android"`, …).
 */
export function makeFiles(
  site: Site,
  ctx: CodegenContext,
  p: Platform,
  platform: "web" | "android" | "ios",
  suffix: string,
  template: string | TemplateFn | undefined
): GeneratedFile[] {
  const render = resolveTemplate(template, platform, ctx.root);
  return site.components.map((comp) => ({
    path: `${comp.name}${suffix}.tsx`,
    content:
      BANNER + render(computeParts(comp, { site, registry: ctx.registry, p })),
  }));
}

/**
 * Resolve a target's `template` option to a {@link TemplateFn}: a function is
 * used as-is; a string is a `.tt` file path (relative to the project root);
 * `undefined` loads the built-in per-platform template. Both file paths are read
 * once and the compiled template is cached.
 */
function resolveTemplate(
  template: string | TemplateFn | undefined,
  platform: "web" | "android" | "ios",
  root: string
): TemplateFn {
  if (typeof template === "function") return template;
  const path = template
    ? resolve(root, template)
    : // Built-ins live at @cnstudio-io/cnstudio/src/generators/<platform>/template.tsx.tt and
      // are copied to dist/generators/… by the build; the path mirrors in both
      // (src/generate ↔ dist/generate are each one level above generators).
      new URL(`../generators/${platform}/template.tsx.tt`, import.meta.url);
  const key = String(path);
  let fn = templateCache.get(key);
  if (!fn) {
    fn = compileTemplate(readFileSync(path, "utf8"));
    templateCache.set(key, fn);
  }
  return fn;
}

const templateCache = new Map<string, TemplateFn>();

/**
 * Compile a `.tt` source string into a {@link TemplateFn} with EJS. Templates
 * reference {@link ComponentParts} fields as locals. Because the output is source
 * code (not HTML), use the **raw** tag `<%- hole %>` — EJS's `<%= %>` would
 * HTML-escape (`<` → `&lt;`) and corrupt the JSX. Full EJS logic (`<% if … %>`,
 * loops, includes) is available. Holes carry their own surrounding whitespace
 * (e.g. `imports` includes the trailing blank line) so simple templates stay a
 * flat substitution.
 */
function compileTemplate(src: string): TemplateFn {
  const tmpl = ejs.compile(src);
  return (parts) => tmpl(parts as unknown as ejs.Data);
}

/**
 * Compute the holes for one component. cnstudio does data binding, not state:
 * expressions are inlined as source with the `$` env (`$props`/`$ctx`) in scope,
 * `$ctx` sourced from `@cnstudio-io/cnstudio/react-web`'s `useDataEnv()`. Only the bindings
 * actually referenced are declared, so the output passes a strict (noUnused*)
 * typecheck in the consuming app.
 */
function computeParts(comp: Component, ctx: Ctx): ComponentParts {
  const meta: Collected = {
    hostTags: new Set(),
    modelComponents: new Set(),
    codeComponents: new Map(),
    exprs: [],
    hasSlot: false,
    hasVariants: false,
  };
  // A component IS its root node — walk it directly.
  collect(comp, ctx, meta, false);
  const tree = nodeToJsx(comp, ctx, 4, false);

  const refersTo = (v: string) => meta.exprs.some((e) => e.includes(v));
  const needsCtx = refersTo("$ctx");
  const needsProps = meta.hasSlot || meta.hasVariants || refersTo("$props");

  // —— imports ——
  let imports = "";
  imports += importCodeComponents(meta.codeComponents);
  for (const name of [...meta.modelComponents].sort()) {
    imports += `import { ${name} } from "./${name}";\n`;
  }
  imports += ctx.p.hostImports(meta.hostTags);
  const rt: string[] = [];
  if (needsCtx) rt.push("useDataEnv");
  if (meta.hasVariants) rt.push("applyVariant");
  if (rt.length) imports += `import { ${rt.sort().join(", ")} } from "@cnstudio-io/cnstudio/react-web";\n`;
  if (imports) imports += "\n"; // blank line before the component, baked into the hole

  // —— signature + `$` bindings ——
  const propsSig = `${needsProps ? "$props" : "_$props"}: Record<string, any> = {}`;
  let setup = "";
  if (needsCtx) setup += `  const $ctx: Record<string, any> = useDataEnv();\n`;

  return {
    name: comp.name,
    imports,
    propsSig,
    setup,
    needsCtx,
    needsProps,
    tree,
    node: comp,
    renderTree: (node, indent = 4) => nodeToJsx(node, ctx, indent, false),
  };
}

/** Group code-component imports by module: `import { A, B as C } from "mod";`,
 *  plus `import Default from "mod";` for default-export components. */
function importCodeComponents(refs: Map<string, ImportSpec>): string {
  const byModule = new Map<string, string[]>();
  let out = "";
  for (const [local, spec] of refs) {
    if (spec.default) {
      out += `import ${local} from ${JSON.stringify(spec.module)};\n`;
      continue;
    }
    const specifier = spec.name === local ? local : `${spec.name} as ${local}`;
    (byModule.get(spec.module) ?? byModule.set(spec.module, []).get(spec.module)!).push(specifier);
  }
  for (const [mod, specs] of byModule) {
    out += `import { ${specs.sort().join(", ")} } from ${JSON.stringify(mod)};\n`;
  }
  return out;
}

/**
 * Pre-pass: gather imports / `$`-var usage so the header can be assembled.
 * `inText` mirrors {@link nodeToJsx} so a wrapped bare string/expr (RN) records
 * the `Text` import it will need.
 */
function collect(node: Node, ctx: Ctx, out: Collected, inText: boolean): void {
  if (typeof node === "string") {
    if (ctx.p.wrapText && !inText) out.hostTags.add("Text");
    return;
  }
  if (node.type === "Slot") { out.hasSlot = true; return; }

  const cls = classify(node.type, ctx);
  let childInText = false;
  if (cls.kind === "instance") out.modelComponents.add(node.type);
  else if (cls.kind === "code") out.codeComponents.set(node.type, cls.spec);
  else {
    // The reserved `Custom` wrapper (div / View).
    out.hostTags.add(ctx.p.wrapperTag);
    childInText = ctx.p.wrapperHoldsText;
  }

  // Each string prop value is a JS expression — record it so `$`-var usage is
  // detected (decides which `$` bindings the component declares).
  if (node.variants) out.hasVariants = true;
  for (const v of Object.values(node.props)) if (typeof v === "string") out.exprs.push(v);
  for (const ov of Object.values(node.variants ?? {})) {
    for (const v of Object.values(ov)) if (typeof v === "string") out.exprs.push(v);
  }
  for (const c of node.children) collect(c, ctx, out, childInText);
}

/**
 * Render a model node to JSX at `indent` spaces. `inText` is whether the parent
 * already renders text (so a string child needs no `<Text>` wrapper on RN).
 */
function nodeToJsx(node: Node, ctx: Ctx, indent: number, inText: boolean): string {
  const pad = " ".repeat(indent);
  const { p } = ctx;

  // Literal text → emitted verbatim. On RN, a bare string not already inside a
  // Text host must be wrapped in <Text>.
  if (typeof node === "string") {
    const t = escapeJsxText(node);
    return p.wrapText && !inText ? `${pad}<Text>${t}</Text>` : `${pad}${t}`;
  }

  // Slot placeholder → render the passed children.
  if (node.type === "Slot") return `${pad}{$props.children}`;

  const cls = classify(node.type, ctx);
  const isWrapper = cls.kind === "wrapper";
  const tag = isWrapper ? p.wrapperTag : node.type;
  const childInText = isWrapper ? p.wrapperHoldsText : false;

  const attrs = node.variants ? variantAttrs(node, p) : propsToJsx(node.props, p);
  const open = attrs ? `${tag} ${attrs}` : tag;

  if (node.children.length === 0) {
    return `${pad}<${open} />`;
  }
  const kids = node.children
    .map((c) => nodeToJsx(c, ctx, indent + 2, childInText))
    .join("\n");
  return `${pad}<${open}>\n${kids}\n${pad}</${tag}>`;
}

/** Variant node: spread the active-variant-merged props (`applyVariant(...)`). */
function variantAttrs(node: Exclude<Node, string>, p: Platform): string {
  const base = serializePropsObject(node.props, p);
  const overrides = serializeVariants(node.variants!, p);
  return `{...applyVariant(${base}, $props.activeVariant, ${overrides})}`;
}

/** `{ "hover": { … }, "mobile": { … } }` — each variant's serialized overrides. */
function serializeVariants(variants: NonNullable<Exclude<Node, string>["variants"]>, p: Platform): string {
  const entries = Object.entries(variants).map(
    ([name, props]) => `${JSON.stringify(name)}: ${serializePropsObject(props, p)}`
  );
  return `{ ${entries.join(", ")} }`;
}

/** Serialize props to an object literal (for variant spreads): `{ "k": <code> }`. */
function serializePropsObject(props: Record<string, unknown>, p: Platform): string {
  const parts: string[] = [];
  for (const [rawKey, value] of Object.entries(props)) {
    if (rawKey === "children") continue;
    const key = p.mapProp(rawKey);
    if (key === null) continue;
    parts.push(`${JSON.stringify(key)}: ${valueCode(key, value)}`);
  }
  return `{ ${parts.join(", ")} }`;
}

/** Serialize props to a JSX attribute string: `title={$props.x} onClick={…}`. */
function propsToJsx(props: Record<string, unknown>, p: Platform): string {
  const parts: string[] = [];
  for (const [rawKey, value] of Object.entries(props)) {
    if (rawKey === "children") continue;
    const key = p.mapProp(rawKey);
    if (key === null) continue; // dropped by the platform

    // A native bare `true` is a flag attr; everything else is a braced
    // expression (string values are JS source) via the shared serializer.
    if (value === true) {
      parts.push(key);
    } else {
      parts.push(`${key}={${valueCode(key, value)}}`);
    }
  }
  return parts.join(" ");
}

/**
 * The source for one prop value. A string value is JS expression source: an `onX`
 * key becomes an arrow over its statement body, any other string is emitted as-is
 * (e.g. `$props.title`, `'flex'`). A non-string is an already-resolved literal.
 */
function valueCode(key: string, value: unknown): string {
  if (typeof value === "string") {
    if (/^on[A-Z]/.test(key)) {
      // The `event` param is emitted only when the action references it.
      const param = /\bevent\b/.test(value) ? "event: any" : "";
      return `(${param}) => { ${value} }`;
    }
    return value;
  }
  return JSON.stringify(value);
}

/** Escape `{`, `}`, `<`, `>` in static text so it survives as JSX content. */
function escapeJsxText(text: string): string {
  return text.replace(/[{}<>]/g, (ch) => `{${JSON.stringify(ch)}}`);
}

// ——— platform factories ———
// Defined in their own generator dirs (alongside each template.tsx.tt) and
// re-exported so `@cnstudio-io/cnstudio/codegen` is the single public import path.
export { web } from "../generators/web";
export { android } from "../generators/android";
export { ios } from "../generators/ios";
