import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import ejs from "ejs";
import {
  instanceOf,
  type Component,
  type Node,
  type Site,
} from "../engine/model";
import type { ImportSpec, RegistryFile } from "../engine/schema";

/**
 * The codegen target API. `studio.config.js` declares a `codegen` array of
 * targets built by the platform factories:
 *
 * ```js
 * import { web, android, ios } from "@cnstudio-io/cnstudio/codegen";
 * export default {
 *   codegen: [
 *     web({ out: "./dist" }),
 *     android({ out: "./android" }),
 *     ios({ out: "./ios" }),
 *   ],
 * };
 * ```
 *
 * Each factory returns a {@link CodegenTarget}: a pure `generate(site, ctx)` that
 * maps the design model ({@link Site}) to a list of {@link GeneratedFile}s. The
 * CLI (`cnstudio generate`) loads the model + registry, runs every target, and
 * writes the files under each target's `out` dir.
 *
 * The output is thin component SOURCE that the consuming app compiles. It
 * delegates the few things that must match the canvas runtime
 * (`$state`, variant merge) to `@cnstudio-io/cnstudio/react-web`, while emitting the tree, the
 * expressions, and the imports as plain source. `web` emits React for the DOM;
 * `android`/`ios` emit React Native (compiled by a React Native app).
 */

/** Options common to every platform factory. */
export interface CodegenTargetOptions {
  /** Output directory for this target, relative to the project root. */
  out: string;
  /**
   * Owns the SHAPE of each generated file. The generator fills the holes
   * ({@link ComponentParts} — `imports`, `name`, `propsSig`, `setup`, `tree`)
   * and the template assembles them, Rails-generator style. Either:
   *   - a **path** to a `.tt` file (relative to the project root) using
   *     `<%= hole %>` tags, or
   *   - a `(parts) => string` function.
   * Defaults to the built-in per-platform template at
   * `@cnstudio-io/cnstudio/src/generators/<platform>/template.tsx.tt`. The DO-NOT-EDIT
   * {@link BANNER} is always prepended afterwards, regardless of template.
   */
  template?: string | TemplateFn;
}

/** A compiled template: fills {@link ComponentParts} into file source. */
export type TemplateFn = (parts: ComponentParts) => string;

/**
 * The holes the generator computes for one component, handed to a
 * {@link CodegenTargetOptions.template}. Everything is pre-rendered source; a
 * template just decides the layout around it (and may re-walk the tree itself
 * via {@link ComponentParts.renderTree}).
 */
export interface ComponentParts {
  /** Component name, e.g. `"Hero"`. */
  name: string;
  /** Assembled import block — code components, sibling `./Name`, host + runtime
   * imports. Ends with a trailing blank line so it drops straight in above the
   * component; `""` when nothing is imported. */
  imports: string;
  /** The function parameter, e.g. `$props: Record<string, any> = {}` (or
   * `_$props…` when props are unused, to satisfy a strict noUnused typecheck). */
  propsSig: string;
  /** `$`-binding lines that go inside the function body before `return`, e.g.
   * `  const $ctx: Record<string, any> = useDataEnv();\n`. `""` when none. A
   * convenience hole: a flat template can drop `<%- setup %>`; a control-flow
   * template can instead branch on {@link ComponentParts.needsCtx}. */
  setup: string;
  /** Whether `$ctx` is referenced (so a template emits the `useDataEnv()` line).
   * Drives the built-in templates via EJS slurp-mode control flow. */
  needsCtx: boolean;
  /** Whether `$props` is referenced (slots / variants / a `$props.` expr). When
   * false {@link ComponentParts.propsSig} names the param `_$props`. */
  needsProps: boolean;
  /** The rendered layer tree as JSX, indented for placement inside `return (…)`. */
  tree: string;
  /** The raw root node, for a template that wants to walk the tree itself. */
  node: Node;
  /** The tree walker, exposed so a custom template can render any node. */
  renderTree(node: Node, indent?: number): string;
}

/** Prepended to every generated file. Generated source is never hand-edited. */
export const BANNER =
  "// This file is auto-generated by cnstudio — DO NOT EDIT.\n" +
  "// Changes are overwritten on the next `cnstudio generate`.\n\n";

/** One file a target wants written, `path` relative to the target's `out` dir. */
export interface GeneratedFile {
  path: string;
  content: string;
}

/** Ambient info a target may need while generating. */
export interface CodegenContext {
  /** Project root (cwd). */
  root: string;
  /** The component registry — resolves code-component (`Button`, …) imports. */
  registry?: RegistryFile;
}

/** A configured output target — the value a platform factory returns. */
export interface CodegenTarget {
  /** Which platform this target emits for. */
  platform: "web" | "android" | "ios";
  /** Output directory, relative to the project root. */
  out: string;
  /** Map the design model to the files to write. Pure — does no I/O. */
  generate(site: Site, ctx: CodegenContext): GeneratedFile[];
}

// The platform factories (`web`, `android`, `ios`) live in their own generator
// dirs alongside their templates — `src/generators/<platform>/index.ts` — and are
// re-exported at the bottom of this file so `@cnstudio-io/cnstudio/codegen` stays the single
// import path. Each calls {@link makeFiles} with its {@link Platform}.

/**
 * Run every target against `site`, writing each {@link GeneratedFile} under the
 * target's `out` dir. Returns the absolute paths written.
 */
export function runCodegen(
  site: Site,
  targets: CodegenTarget[],
  ctx: CodegenContext
): string[] {
  const written: string[] = [];
  for (const target of targets) {
    const outDir = resolve(ctx.root, target.out);
    for (const file of target.generate(site, ctx)) {
      const dest = join(outDir, file.path);
      mkdirSync(dirname(dest), { recursive: true });
      writeFileSync(dest, file.content);
      written.push(dest);
    }
  }
  return written;
}

// ——— platforms ———

/**
 * A platform's emit rules. The web and React Native paths share one tree walk and
 * differ only in: the element a UI-created component's root (`Custom`) wraps its
 * children in, whether bare text must be wrapped (RN forbids raw strings outside
 * `<Text>`), which props are renamed / dropped, and the import line for the host
 * components used. (Nodes only ever instance registered components or the reserved
 * `Custom`/`slot` — there are no arbitrary host tags to map.)
 */
export interface Platform {
  /** The element a `Custom` root emits as: `div` (web) or `View` (React Native). */
  wrapperTag: string;
  /** Whether the wrapper renders its children as text (so no `<Text>` wrap). The
   *  DOM lets any element hold text; RN's `View` does not. */
  wrapperHoldsText: boolean;
  /** Whether a bare string/expr child must be wrapped (RN) when not already in text. */
  wrapText: boolean;
  /** Rename / drop a prop key; return null to drop it. */
  mapProp(key: string): string | null;
  /** Import line(s) for the host components actually used (`View`/`Text` on RN). */
  hostImports(usedHostTags: Set<string>): string;
}

/** The web (DOM) platform: the `Custom` wrapper is a `<div>`; props pass through. */
export const WEB: Platform = {
  wrapperTag: "div",
  wrapperHoldsText: true, // the DOM lets any element hold text
  wrapText: false,
  mapProp: (key) => key,
  hostImports: () => "", // DOM intrinsics need no import
};

/** The React Native platform (shared by `android` and `ios`): the `Custom`
 *  wrapper is a `<View>`, and bare text is wrapped in `<Text>`. */
export function reactNativePlatform(): Platform {
  return {
    wrapperTag: "View",
    wrapperHoldsText: false, // a View can't hold raw text — see wrapText
    wrapText: true,
    mapProp: (key) => {
      if (key === "className") return null; // RN has no className
      if (key === "onClick") return "onPress";
      return key;
    },
    hostImports: (used) =>
      used.size
        ? `import { ${[...used].sort().join(", ")} } from "react-native";\n`
        : "",
  };
}

// ——— emitter ———

/** Per-file emit context threaded through the walk. */
interface Ctx {
  site: Site;
  registry?: RegistryFile;
  p: Platform;
  /** Local JSX name per code-component node type (a registry id) — see {@link localNameFor}. */
  locals: Map<string, string>;
  /** The component declares a NAMED slot, so every marker emits a `pickSlot`
   * filter over `$props.children` (set after {@link collect}, read in the emit). */
  namedSlots?: boolean;
}

/** Renderable built-in primitives — emitted as imports from the cnstudio runtime
 *  (`@cnstudio-io/cnstudio/react-web`). `Slot` and `Loop` are engine-handled in
 *  the walk, so they are intentionally excluded here. */
const RUNTIME_PRIMITIVES = new Set(["DomElement", "HorizontalStack", "VerticalStack"]);

/** How a node's `type` resolves: another designed component, a registered code
 * component (with its import), or the reserved `Custom` wrapper. */
type Kind =
  | { kind: "instance" }
  | { kind: "code"; spec: ImportSpec }
  | { kind: "wrapper" };

function classify(type: string, ctx: Ctx): Kind {
  // A QUALIFIED name (`@/path/to/module#Export`) is a registry id — a code
  // component. Code and design components live in separate namespaces: qualified
  // names address the registry, bare names the design's own components. A
  // qualified name that isn't in the registry is an error, never a fallthrough.
  if (type.includes("#")) {
    const meta = ctx.registry?.components?.[type];
    if (!meta) {
      throw new Error(
        `cannot generate <${type}>: not in the component registry ` +
          "(qualified `@/module#Export` node types must match a registry id)."
      );
    }
    return { kind: "code", spec: meta.import };
  }
  // BARE names resolve against the design's own components…
  if (instanceOf({ type, props: {}, children: [] }, ctx.site)) return { kind: "instance" };
  // …and the built-in layout primitives, which ship with cnstudio (not the
  // project) and aren't in registry.json — they're merged into the runtime
  // registry only. Emit them as code components imported from the cnstudio
  // runtime so the design can place them anywhere without the project
  // registering anything. (`Slot`/`Loop` are engine-handled — see nodeToJsx —
  // and never reach here.)
  if (RUNTIME_PRIMITIVES.has(type)) {
    return { kind: "code", spec: { module: "@cnstudio-io/cnstudio/react-web", name: type } };
  }
  // The ONLY other type a valid model carries is the reserved `Custom` (a
  // UI-created component's root), emitted as the platform wrapper element.
  // Anything else — a raw host tag (`div`, `span`, …) or a code component
  // referenced by bare export name — is NOT a valid node. Fail the build rather
  // than emit something ambiguous from a hand-edited / corrupt site.json.
  if (type === "Custom") return { kind: "wrapper" };
  throw new Error(
    `cannot generate <${type}>: not a design component. Bare node types resolve ` +
      "against the design's own components (and built-in primitives); a code " +
      "component is addressed by its registry id (`@/module#Export`)."
  );
}

/**
 * The local JSX identifier a code-component node type renders as — its export
 * name, suffixed (`Icon$2`) when two different modules export the same name in
 * one file, and never colliding with a design component's `./Name` import.
 * Cached on {@link Ctx.locals}, so `collect` and `nodeToJsx` (which walk in the
 * same order) agree.
 */
function localNameFor(type: string, spec: ImportSpec, ctx: Ctx): string {
  const cached = ctx.locals.get(type);
  if (cached) return cached;
  const taken = new Set<string>([
    ...ctx.locals.values(),
    ...ctx.site.components.map((c) => c.name),
  ]);
  let local = spec.name;
  for (let i = 2; taken.has(local); i++) local = `${spec.name}$${i}`;
  ctx.locals.set(type, local);
  return local;
}

/** What the tree walk collects, so the file header can be assembled correctly. */
interface Collected {
  /** Host components actually emitted (`View`/`Text` on RN) — for the import line. */
  hostTags: Set<string>;
  /** Other designed components referenced — emitted as `./Name` sibling imports. */
  modelComponents: Set<string>;
  /** Registered code components referenced → their import spec, keyed by local name. */
  codeComponents: Map<string, ImportSpec>;
  /** Every expression string in the tree (decides which `$` vars to bind). */
  exprs: string[];
  /** Whether a `<slot>` appears (so `$props.children` is referenced). */
  hasSlot: boolean;
  /** The names of the Slot markers found (`""` = the default slot). Any named
   * marker switches the component to `pickSlot`-filtered emission. */
  slotNames: Set<string>;
  /** Whether any node carries variant overrides (so `$props.activeVariant` is read). */
  hasVariants: boolean;
  /** Whether a `Loop` appears (so `Fragment` is imported for the keyed iterations). */
  hasLoop: boolean;
}

/**
 * Generate one file per component for a target: resolve its template once, then
 * for each component compute the {@link ComponentParts}, render them, and prepend
 * the DO-NOT-EDIT {@link BANNER} (enforced here, whatever shape the template has).
 * `suffix` is the platform tag in the filename (`""` for web, `".android"`, …).
 */
export function makeFiles(
  site: Site,
  ctx: CodegenContext,
  p: Platform,
  platform: "web" | "android" | "ios",
  suffix: string,
  template: string | TemplateFn | undefined
): GeneratedFile[] {
  const render = resolveTemplate(template, platform, ctx.root);
  return site.components.map((comp) => ({
    path: `${comp.name}${suffix}.tsx`,
    content:
      BANNER +
      render(computeParts(comp, { site, registry: ctx.registry, p, locals: new Map() })),
  }));
}

/**
 * Resolve a target's `template` option to a {@link TemplateFn}: a function is
 * used as-is; a string is a `.tt` file path (relative to the project root);
 * `undefined` loads the built-in per-platform template. Both file paths are read
 * once and the compiled template is cached.
 */
function resolveTemplate(
  template: string | TemplateFn | undefined,
  platform: "web" | "android" | "ios",
  root: string
): TemplateFn {
  if (typeof template === "function") return template;
  const path = template
    ? resolve(root, template)
    : // Built-ins live at @cnstudio-io/cnstudio/src/generators/<platform>/template.tsx.tt and
      // are copied to dist/generators/… by the build; the path mirrors in both
      // (src/generate ↔ dist/generate are each one level above generators).
      new URL(`../generators/${platform}/template.tsx.tt`, import.meta.url);
  const key = String(path);
  let fn = templateCache.get(key);
  if (!fn) {
    fn = compileTemplate(readFileSync(path, "utf8"));
    templateCache.set(key, fn);
  }
  return fn;
}

const templateCache = new Map<string, TemplateFn>();

/**
 * Compile a `.tt` source string into a {@link TemplateFn} with EJS. Templates
 * reference {@link ComponentParts} fields as locals. Because the output is source
 * code (not HTML), use the **raw** tag `<%- hole %>` — EJS's `<%= %>` would
 * HTML-escape (`<` → `&lt;`) and corrupt the JSX. Full EJS logic (`<% if … %>`,
 * loops, includes) is available. Holes carry their own surrounding whitespace
 * (e.g. `imports` includes the trailing blank line) so simple templates stay a
 * flat substitution.
 */
function compileTemplate(src: string): TemplateFn {
  const tmpl = ejs.compile(src);
  return (parts) => tmpl(parts as unknown as ejs.Data);
}

/**
 * Compute the holes for one component. cnstudio does data binding, not state:
 * expressions are inlined as source with the `$` env (`$props`/`$ctx`) in scope,
 * `$ctx` sourced from `@cnstudio-io/cnstudio/react-web`'s `useDataEnv()`. Only the bindings
 * actually referenced are declared, so the output passes a strict (noUnused*)
 * typecheck in the consuming app.
 */
function computeParts(comp: Component, ctx: Ctx): ComponentParts {
  const meta: Collected = {
    hostTags: new Set(),
    modelComponents: new Set(),
    codeComponents: new Map(),
    exprs: [],
    hasSlot: false,
    slotNames: new Set(),
    hasVariants: false,
    hasLoop: false,
  };
  // A component IS its root node — walk it directly.
  collect(comp, ctx, meta, false);
  // Any NAMED marker means the children must be routed, so every marker in this
  // component (the unnamed default included) emits a `pickSlot` filter.
  ctx.namedSlots = [...meta.slotNames].some((n) => n !== "");
  const tree = nodeToJsx(comp, ctx, 4, false, false);

  const refersTo = (v: string) => meta.exprs.some((e) => e.includes(v));
  const needsCtx = refersTo("$ctx");
  const needsProps = meta.hasSlot || meta.hasVariants || refersTo("$props");

  // —— imports ——
  let imports = "";
  if (meta.hasLoop) imports += `import { Fragment } from "react";\n`;
  imports += importCodeComponents(meta.codeComponents);
  for (const name of [...meta.modelComponents].sort()) {
    imports += `import { ${name} } from "./${name}";\n`;
  }
  imports += ctx.p.hostImports(meta.hostTags);
  const rt: string[] = [];
  if (needsCtx) rt.push("useDataEnv");
  if (meta.hasVariants) rt.push("applyVariant");
  if (meta.hasSlot && ctx.namedSlots) rt.push("pickSlot");
  if (rt.length) imports += `import { ${rt.sort().join(", ")} } from "@cnstudio-io/cnstudio/react-web";\n`;
  if (imports) imports += "\n"; // blank line before the component, baked into the hole

  // —— signature + `$` bindings ——
  const propsSig = `${needsProps ? "$props" : "_$props"}: Record<string, any> = {}`;
  let setup = "";
  if (needsCtx) setup += `  const $ctx: Record<string, any> = useDataEnv();\n`;

  return {
    name: comp.name,
    imports,
    propsSig,
    setup,
    needsCtx,
    needsProps,
    tree,
    node: comp,
    renderTree: (node, indent = 4) => nodeToJsx(node, ctx, indent, false, false),
  };
}

/** Group code-component imports by module: `import { A, B as C } from "mod";`,
 *  plus `import Default from "mod";` for default-export components. */
function importCodeComponents(refs: Map<string, ImportSpec>): string {
  const byModule = new Map<string, string[]>();
  let out = "";
  for (const [local, spec] of refs) {
    if (spec.default) {
      out += `import ${local} from ${JSON.stringify(spec.module)};\n`;
      continue;
    }
    const specifier = spec.name === local ? local : `${spec.name} as ${local}`;
    (byModule.get(spec.module) ?? byModule.set(spec.module, []).get(spec.module)!).push(specifier);
  }
  for (const [mod, specs] of byModule) {
    out += `import { ${specs.sort().join(", ")} } from ${JSON.stringify(mod)};\n`;
  }
  return out;
}

/**
 * Pre-pass: gather imports / `$`-var usage so the header can be assembled.
 * `inText` mirrors {@link nodeToJsx} so a wrapped bare string/expr (RN) records
 * the `Text` import it will need.
 */
function collect(node: Node, ctx: Ctx, out: Collected, inText: boolean): void {
  if (typeof node === "string") {
    if (ctx.p.wrapText && !inText) out.hostTags.add("Text");
    return;
  }
  if (node.type === "Slot") {
    out.hasSlot = true;
    // A marker's `name` is a RAW literal string ("" = the default slot).
    out.slotNames.add(typeof node.props.name === "string" ? node.props.name : "");
    return;
  }

  // Loop is engine-handled (no component to import); its `data` prop is an
  // expression and its children are the per-iteration template.
  if (node.type === "Loop") {
    out.hasLoop = true;
    for (const v of Object.values(node.props)) if (typeof v === "string") out.exprs.push(v);
    for (const c of node.children) collect(c, ctx, out, inText);
    return;
  }

  const cls = classify(node.type, ctx);
  let childInText = false;
  if (cls.kind === "instance") out.modelComponents.add(node.type);
  else if (cls.kind === "code") out.codeComponents.set(localNameFor(node.type, cls.spec, ctx), cls.spec);
  else {
    // The reserved `Custom` wrapper (div / View).
    out.hostTags.add(ctx.p.wrapperTag);
    childInText = ctx.p.wrapperHoldsText;
  }

  // Each string prop value is a JS expression — record it so `$`-var usage is
  // detected (decides which `$` bindings the component declares).
  if (node.variants) out.hasVariants = true;
  for (const v of Object.values(node.props)) if (typeof v === "string") out.exprs.push(v);
  for (const ov of Object.values(node.variants ?? {})) {
    for (const v of Object.values(ov)) if (typeof v === "string") out.exprs.push(v);
  }
  for (const c of node.children) collect(c, ctx, out, childInText);
}

/**
 * Render a model node to JSX at `indent` spaces. `inText` is whether the parent
 * already renders text (so a string child needs no `<Text>` wrapper on RN).
 */
function nodeToJsx(node: Node, ctx: Ctx, indent: number, inText: boolean, inLoop: boolean): string {
  const pad = " ".repeat(indent);
  const { p } = ctx;

  // Literal text → emitted verbatim. On RN, a bare string not already inside a
  // Text host must be wrapped in <Text>.
  if (typeof node === "string") {
    const t = escapeJsxText(node);
    return p.wrapText && !inText ? `${pad}<Text>${t}</Text>` : `${pad}${t}`;
  }

  // Slot placeholder → render the passed children. A component with any NAMED
  // marker routes: each marker filters `$props.children` by the reserved `slot`
  // prop via `pickSlot` (`""` = children with no routing prop). With only
  // unnamed markers the children pass through whole, as before. A marker that
  // is itself a fill of an inner instance (it carries its own `slot` routing
  // prop) FORWARDS: the picked children are re-tagged with that routing prop so
  // the inner component's filter routes them onward.
  if (node.type === "Slot") {
    if (!ctx.namedSlots) return `${pad}{$props.children}`;
    const name = typeof node.props.name === "string" ? node.props.name : "";
    const routeTo = typeof node.props.slot === "string" ? node.props.slot : undefined;
    const route = routeTo === undefined ? "" : `, ${JSON.stringify(routeTo)}`;
    return `${pad}{pickSlot($props.children, ${JSON.stringify(name)}${route})}`;
  }

  // Loop → `data.map(...)`, the children rendered once per element with the
  // element bound under `$loop.<name>` (`.current` / `.index` / `.all`) —
  // mirroring the canvas runtime (NodeWrapper). The enclosing `$loop` env is
  // passed INTO the IIFE (`{}` at the top level) so the shadowing `const $loop`
  // inside the callback can extend it without a TDZ self-reference.
  if (node.type === "Loop") {
    const dataExpr =
      typeof node.props.data === "string" ? node.props.data : JSON.stringify(node.props.data ?? []);
    const name = typeof node.props.name === "string" && node.props.name ? node.props.name : "item";
    const kids = node.children
      .map((c) => nodeToJsx(c, ctx, indent + 6, inText, true))
      .join("\n");
    // Bind `$loop` only when the template actually reads it, so the output
    // passes a strict (noUnused*) typecheck in the consuming app.
    if (loopVarNeeded(node.children)) {
      return (
        `${pad}{((__data: unknown, __outer: Record<string, any>) =>\n` +
        `${pad}  (Array.isArray(__data) ? __data : []).map((current: any, index: number, all: any[]) => {\n` +
        `${pad}    const $loop: Record<string, any> = { ...__outer, ${JSON.stringify(name)}: { current, index, all } };\n` +
        `${pad}    return (\n` +
        `${pad}      <Fragment key={index}>\n` +
        `${kids}\n` +
        `${pad}      </Fragment>\n` +
        `${pad}    );\n` +
        `${pad}  }))(${dataExpr}, ${inLoop ? "$loop" : "{}"})}`
      );
    }
    return (
      `${pad}{((__data: unknown) =>\n` +
      `${pad}  (Array.isArray(__data) ? __data : []).map((_current: any, index: number) => (\n` +
      `${pad}    <Fragment key={index}>\n` +
      `${kids}\n` +
      `${pad}    </Fragment>\n` +
      `${pad}  )))(${dataExpr})}`
    );
  }

  // `hidden` mirrors the runtime (resolveProps): a truthy value renders nothing.
  // Emitted as a conditional rather than passed through — as a DOM attribute any
  // CSS display rule on the component would beat the UA [hidden] rule.
  if (node.props.hidden !== undefined && !node.variants) {
    const cond =
      typeof node.props.hidden === "string" ? node.props.hidden : JSON.stringify(node.props.hidden);
    const rest: Exclude<Node, string> = {
      ...node,
      props: Object.fromEntries(Object.entries(node.props).filter(([k]) => k !== "hidden")),
    };
    const inner = nodeToJsx(rest, ctx, indent + 2, inText, inLoop);
    return `${pad}{!(${cond}) && (\n${inner}\n${pad})}`;
  }

  const cls = classify(node.type, ctx);
  const isWrapper = cls.kind === "wrapper";
  const tag = isWrapper
    ? p.wrapperTag
    : cls.kind === "code"
      ? localNameFor(node.type, cls.spec, ctx)
      : node.type;
  const childInText = isWrapper ? p.wrapperHoldsText : false;

  const attrs = node.variants ? variantAttrs(node, p) : propsToJsx(node.props, p);
  const open = attrs ? `${tag} ${attrs}` : tag;

  if (node.children.length === 0) {
    return `${pad}<${open} />`;
  }
  const kids = node.children
    .map((c) => nodeToJsx(c, ctx, indent + 2, childInText, inLoop))
    .join("\n");
  return `${pad}<${open}>\n${kids}\n${pad}</${tag}>`;
}

/**
 * Whether a loop's template (or a nested loop under it) reads `$loop` — i.e.
 * any string prop expression in the subtree mentions it. Decides whether the
 * emitted map callback declares the `$loop` binding.
 */
function loopVarNeeded(children: Node[]): boolean {
  return children.some((c) => {
    if (typeof c === "string") return false;
    const inProps = (props: Record<string, unknown>) =>
      Object.values(props).some((v) => typeof v === "string" && v.includes("$loop"));
    if (inProps(c.props)) return true;
    if (Object.values(c.variants ?? {}).some(inProps)) return true;
    return loopVarNeeded(c.children);
  });
}

/** Variant node: spread the active-variant-merged props (`applyVariant(...)`). */
function variantAttrs(node: Exclude<Node, string>, p: Platform): string {
  const base = serializePropsObject(node.props, p);
  const overrides = serializeVariants(node.variants!, p);
  return `{...applyVariant(${base}, $props.activeVariant, ${overrides})}`;
}

/** `{ "hover": { … }, "mobile": { … } }` — each variant's serialized overrides. */
function serializeVariants(variants: NonNullable<Exclude<Node, string>["variants"]>, p: Platform): string {
  const entries = Object.entries(variants).map(
    ([name, props]) => `${JSON.stringify(name)}: ${serializePropsObject(props, p)}`
  );
  return `{ ${entries.join(", ")} }`;
}

/** Serialize props to an object literal (for variant spreads): `{ "k": <code> }`. */
function serializePropsObject(props: Record<string, unknown>, p: Platform): string {
  const parts: string[] = [];
  for (const [rawKey, value] of Object.entries(props)) {
    if (rawKey === "children") continue;
    const key = p.mapProp(rawKey);
    if (key === null) continue;
    parts.push(`${JSON.stringify(key)}: ${valueCode(key, value)}`);
  }
  return `{ ${parts.join(", ")} }`;
}

/** Serialize props to a JSX attribute string: `title={$props.x} onClick={…}`. */
function propsToJsx(props: Record<string, unknown>, p: Platform): string {
  const parts: string[] = [];
  for (const [rawKey, value] of Object.entries(props)) {
    if (rawKey === "children") continue;
    const key = p.mapProp(rawKey);
    if (key === null) continue; // dropped by the platform

    // A native bare `true` is a flag attr; everything else is a braced
    // expression (string values are JS source) via the shared serializer.
    if (value === true) {
      parts.push(key);
    } else {
      parts.push(`${key}={${valueCode(key, value)}}`);
    }
  }
  return parts.join(" ");
}

/**
 * The source for one prop value. A string value is JS expression source: an `onX`
 * key becomes an arrow over its statement body, any other string is emitted as-is
 * (e.g. `$props.title`, `'flex'`). A non-string is an already-resolved literal.
 */
function valueCode(key: string, value: unknown): string {
  if (typeof value === "string") {
    if (/^on[A-Z]/.test(key)) {
      // The `event` param is emitted only when the action references it.
      const param = /\bevent\b/.test(value) ? "event: any" : "";
      return `(${param}) => { ${value} }`;
    }
    // The reserved slot-routing prop is a RAW literal name, not an expression —
    // the enclosing component's `pickSlot` filter reads it off the element.
    if (key === "slot") return JSON.stringify(value);
    return value;
  }
  return JSON.stringify(value);
}

/** Escape `{`, `}`, `<`, `>` in static text so it survives as JSX content. */
function escapeJsxText(text: string): string {
  return text.replace(/[{}<>]/g, (ch) => `{${JSON.stringify(ch)}}`);
}

// ——— platform factories ———
// Defined in their own generator dirs (alongside each template.tsx.tt) and
// re-exported so `@cnstudio-io/cnstudio/codegen` is the single public import path.
export { web } from "../generators/web";
export { android } from "../generators/android";
export { ios } from "../generators/ios";
