// @vitest-environment node
// Codegen is pure Node — it reads its built-in .tt templates from disk relative
// to import.meta.url, which jsdom would root at "/". Run under node so the real
// file URL resolves.
import { describe, expect, it } from "vitest";
import { android, ios, web } from "./codegen";
import type { Site } from "../engine/model";
import type { RegistryFile } from "../engine/schema";

// Prop VALUES are JS expression source: `"$props.title"` is a binding, `"'/a.png'"`
// a literal string. Children are component instances and literal text strings.
const site: Site = {
  components: [
    {
      // A component IS a node: type/props/children directly, no `root` wrapper.
      // A UI-created component's root carries the reserved type "Custom".
      name: "Card",
      type: "Custom",
      props: { title: "$props.title", onClick: "$ctx.toggle()" },
      children: [
        "Hello",
        { type: "img", props: { src: "'/a.png'" }, children: [] },
        { type: "slot", props: {}, children: [] },
      ],
    },
  ],
};

describe("web target", () => {
  const [file] = web({ out: "./dist" }).generate(site, { root: "/x" });

  it("emits one .tsx per component", () => {
    expect(file.path).toBe("Card.tsx");
  });

  it("prepends a DO-NOT-EDIT banner to generated files", () => {
    expect(file.content.startsWith("// This file is auto-generated by cnstudio — DO NOT EDIT.")).toBe(true);
  });

  it("sources $ctx from useDataEnv (data binding, no state)", () => {
    expect(file.content).toContain('import { useDataEnv } from "@cnstudio-io/cnstudio/react-web";');
    expect(file.content).toContain("const $ctx: Record<string, any> = useDataEnv();");
    expect(file.content).not.toContain("use$State");
  });

  it("emits prop expressions, an event handler, and the slot", () => {
    expect(file.content).toContain('export function Card($props: Record<string, any> = {})');
    expect(file.content).toContain("title={$props.title}"); // a prop-value binding
    expect(file.content).toContain("onClick={() => { $ctx.toggle() }}"); // no event ref → no param
    expect(file.content).toContain("<img src={'/a.png'} />"); // literal string prop value
    expect(file.content).toContain("{$props.children}"); // slot
  });

  it('emits a "Custom" root as a plain <div> wrapper', () => {
    expect(file.content).toContain("<div title={$props.title}");
  });
});

describe("code-component imports", () => {
  const registry: RegistryFile = {
    components: {
      Button: { import: { module: "@/components/ui/button", name: "Button" }, props: {} },
    },
  };
  const withButton: Site = {
    components: [
      {
        name: "Bar",
        type: "Custom",
        props: {},
        children: [{ type: "Button", props: { variant: "'ghost'" }, children: ["Go"] }],
      },
    ],
  };

  it("imports registered code components from their real module", () => {
    const [file] = web({ out: "./d" }).generate(withButton, { root: "/x", registry });
    expect(file.content).toContain('import { Button } from "@/components/ui/button";');
    expect(file.content).toContain("<Button variant={'ghost'}>");
  });
});

describe("variants", () => {
  const variantSite: Site = {
    components: [
      {
        name: "Box",
        variantNames: ["active"],
        type: "Custom",
        props: { className: "'box'" },
        variants: { active: { className: "'box on'" } },
        children: ["hi"],
      },
    ],
  };

  it("emits applyVariant() driven by $props.activeVariant", () => {
    const [file] = web({ out: "./d" }).generate(variantSite, { root: "/x" });
    expect(file.content).toContain('import { applyVariant } from "@cnstudio-io/cnstudio/react-web";');
    expect(file.content).toContain(
      '{...applyVariant({ "className": \'box\' }, $props.activeVariant, { "active": { "className": \'box on\' } })}'
    );
  });
});

describe("custom template", () => {
  it("lets studio.config own the file shape, banner still enforced", () => {
    const [file] = web({
      out: "./d",
      template: (c) => `"use client";\n${c.imports}\nexport default function ${c.name}(${c.propsSig}) {\n${c.setup}  return (\n${c.tree}\n  );\n}\n`,
    }).generate(site, { root: "/x" });

    expect(file.content.startsWith("// This file is auto-generated by cnstudio — DO NOT EDIT.")).toBe(true);
    expect(file.content).toContain('"use client";');
    expect(file.content).toContain("export default function Card($props: Record<string, any> = {})");
    expect(file.content).toContain("title={$props.title}"); // tree hole filled
  });
});

describe("react native targets", () => {
  it("maps tags to RN, imports only used host components, renames onClick→onPress", () => {
    const [file] = android({ out: "./android" }).generate(site, { root: "/x" });
    expect(file.path).toBe("Card.android.tsx");
    expect(file.content).toContain('import { Image, Text, View } from "react-native";');
    expect(file.content).toContain("<View");
    expect(file.content).toContain("onPress={() =>");
    expect(file.content).not.toContain("className");
    expect(file.content).toContain("<Image");
  });

  it("wraps a bare literal-text child in <Text>", () => {
    const [file] = android({ out: "./android" }).generate(site, { root: "/x" });
    expect(file.content).toContain("<Text>Hello</Text>");
  });

  it("ios uses the .ios.tsx suffix", () => {
    const [file] = ios({ out: "./ios" }).generate(site, { root: "/x" });
    expect(file.path).toBe("Card.ios.tsx");
  });
});
